execute:
  freeze: auto

project:
  type: website

website:
  title: "Computational Text Analysis with Python"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: basic-python.qmd
      - text: Basics of Python

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true



