[project]
name = "0-python-intro"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pip>=25.3",
    "scipy>=1.16.2",
    "seaborn>=0.13.2",
    "spacy>=3.8.7",
]
